server:
  port: 8080

spring:
  application:
    name: backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jobtracker}
    username: ${SPRING_DATASOURCE_USERNAME:jobtracker}
    password: ${SPRING_DATASOURCE_PASSWORD:jobtracker_hush}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true